# Generated by Django 4.2.6 on 2023-10-24 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100, verbose_name='место')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='время')),
                ('habit_action', models.TextField(verbose_name='действие')),
                ('is_pleasant', models.BooleanField(default=True, verbose_name='Признак приятной привычки')),
                ('period', models.CharField(choices=[('HOURLY', 'каждый час'), ('DAILY', 'каждый день'), ('WEEKLY', 'каждую неделю')], default='DAILY', max_length=15, verbose_name='Периодичность')),
                ('reward', models.TextField(blank=True, null=True, verbose_name='Вознаграждение')),
                ('time_to_complete', models.TimeField(blank=True, default=datetime.timedelta(seconds=60), null=True, verbose_name='Время на выполнение')),
                ('is_public', models.BooleanField(default=False, verbose_name='Признак публичности')),
            ],
            options={
                'verbose_name': 'приятная привычка',
                'verbose_name_plural': 'приятные привычки',
            },
        ),
    ]
